name: Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  brew-style:
    runs-on: macos-14
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Brew style
        run: brew style Casks/nav-center.rb
